name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      # Step to check out the repository code
      - uses: actions/checkout@v2

      # Step to set up the specified Node.js version
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      # ✅ FIX: Install build tools required by better-sqlite3
      - name: Install system dependencies for better-sqlite3
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 make g++ build-essential

      # Step to install dependencies
      - name: Install dependencies
        run: |
          npm install --build-from-source=false

      # Step to run the bot with the correct port
      - name: Start the bot
        env:
          PORT: 8080
        run: npm start
